export const categories = [
  "Poet",
  "Scientist",
  "Humanitarian",
  "Political Leader",
  "Artist",
  "Musician",
  "Writer",
  "Educator",
  "Social Reformer",
  "Athlete",
];

export const provinces = [
  "Punjab",
  "Sindh",
  "Balochistan",
  "Khyber Pakhtunkhwa",
  "Gilgit-Baltistan",
  "Azad Kashmir",
  "Islamabad",
];

export const eras = ["Pre-1947", "1947-1970", "1971-2000", "2001-Present"];

export const personalities = [
  {
    id: "allama-iqbal",
    name: "Allama Muhammad Iqbal",
    urduName: "علامہ محمد اقبال",
    category: "Poet",
    province: "Punjab",
    city: "Sialkot",
    coordinates: [32.4945, 74.5229],
    lifeDates: "1877-1938",
    impactScore: 99,
    era: "Pre-1947",
    portrait: "https://commons.wikimedia.org/wiki/Special:FilePath/Allama%20Iqbal.jpg?width=240",
    bio: "Poet-philosopher whose work gave intellectual force to Muslim selfhood in South Asia and became central to Pakistan's cultural imagination.",
    achievements: [
      "Recognized as Pakistan's national poet",
      "Authored Bang-e-Dra, Asrar-e-Khudi, and Javid Nama",
      "Developed a philosophy of selfhood, renewal, and civic awakening",
    ],
    sources: [
      { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Muhammad_Iqbal" },
      { label: "Britannica", url: "https://www.britannica.com/biography/Muhammad-Iqbal" },
    ],
    relatedPeople: ["Faiz Ahmed Faiz", "Fatima Jinnah"],
  },
  {
    id: "abdus-salam",
    name: "Abdus Salam",
    urduName: "عبد السلام",
    category: "Scientist",
    province: "Punjab",
    city: "Jhang",
    coordinates: [31.2681, 72.3181],
    lifeDates: "1926-1996",
    impactScore: 98,
    era: "1947-1970",
    portrait: "https://commons.wikimedia.org/wiki/Special:FilePath/Abdus%20Salam%201987.jpg?width=240",
    bio: "Theoretical physicist and Nobel laureate whose electroweak work placed Pakistan inside one of modern physics' defining achievements.",
    achievements: [
      "Shared the 1979 Nobel Prize in Physics",
      "Helped develop electroweak unification theory",
      "Founded the International Centre for Theoretical Physics",
    ],
    sources: [
      { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Abdus_Salam" },
      { label: "Nobel Prize", url: "https://www.nobelprize.org/prizes/physics/1979/salam/biographical/" },
    ],
    relatedPeople: ["Atta-ur-Rahman", "Arfa Karim"],
  },
  {
    id: "abdul-sattar-edhi",
    name: "Abdul Sattar Edhi",
    urduName: "عبد الستار ایدھی",
    category: "Humanitarian",
    province: "Sindh",
    city: "Karachi",
    coordinates: [24.8607, 67.0011],
    lifeDates: "1928-2016",
    impactScore: 97,
    era: "1971-2000",
    portrait: "https://commons.wikimedia.org/wiki/Special:FilePath/Abdul%20Sattar%20Edhi.jpg?width=240",
    bio: "Humanitarian who built one of the world's largest volunteer ambulance and welfare networks from Karachi.",
    achievements: [
      "Founded the Edhi Foundation",
      "Built a nationwide ambulance, shelter, and care network",
      "Became a global symbol of service without status",
    ],
    sources: [
      { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Abdul_Sattar_Edhi" },
      { label: "Edhi Foundation", url: "https://edhi.org/" },
    ],
    relatedPeople: ["Ruth Pfau", "Hakeem Muhammad Saeed"],
  },
  {
    id: "fatima-jinnah",
    name: "Fatima Jinnah",
    urduName: "فاطمہ جناح",
    category: "Political Leader",
    province: "Sindh",
    city: "Karachi",
    coordinates: [24.8849, 67.0444],
    lifeDates: "1893-1967",
    impactScore: 94,
    era: "Pre-1947",
    portrait: "https://commons.wikimedia.org/wiki/Special:FilePath/Fatima%20Jinnah.jpg?width=240",
    bio: "Pakistan movement leader remembered as Madar-e-Millat and as a symbol of civic courage, democracy, and women's public leadership.",
    achievements: [
      "Prominent Pakistan movement figure",
      "Known as Madar-e-Millat, Mother of the Nation",
      "Led a historic opposition presidential campaign in 1965",
    ],
    sources: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Fatima_Jinnah" }],
    relatedPeople: ["Allama Muhammad Iqbal", "Benazir Bhutto"],
  },
  {
    id: "faiz-ahmed-faiz",
    name: "Faiz Ahmed Faiz",
    urduName: "فیض احمد فیض",
    category: "Poet",
    province: "Punjab",
    city: "Lahore",
    coordinates: [31.5204, 74.3587],
    lifeDates: "1911-1984",
    impactScore: 93,
    era: "1947-1970",
    portrait: "https://commons.wikimedia.org/wiki/Special:FilePath/Faiz%20Ahmad%20Faiz.jpg?width=240",
    bio: "Poet, editor, and public intellectual whose lyrical politics shaped modern Urdu literature across Pakistan and beyond.",
    achievements: [
      "Received the Lenin Peace Prize",
      "Authored major modern Urdu poetry collections",
      "Influenced generations of writers, musicians, and activists",
    ],
    sources: [
      { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Faiz_Ahmad_Faiz" },
      { label: "Britannica", url: "https://www.britannica.com/biography/Faiz-Ahmed-Faiz" },
    ],
    relatedPeople: ["Allama Muhammad Iqbal", "Ahmed Faraz"],
  },
  {
    id: "benazir-bhutto",
    name: "Benazir Bhutto",
    urduName: "بینظیر بھٹو",
    category: "Political Leader",
    province: "Sindh",
    city: "Larkana",
    coordinates: [27.557, 68.2028],
    lifeDates: "1953-2007",
    impactScore: 92,
    era: "1971-2000",
    portrait: "https://commons.wikimedia.org/wiki/Special:FilePath/Benazir%20Bhutto%201989.jpg?width=240",
    bio: "Twice elected prime minister and the first woman to lead a democratic government in a Muslim-majority country.",
    achievements: [
      "Served two terms as Prime Minister of Pakistan",
      "Global symbol of women's political leadership",
      "Central figure in Pakistan's late 20th-century democratic politics",
    ],
    sources: [
      { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Benazir_Bhutto" },
      { label: "Britannica", url: "https://www.britannica.com/biography/Benazir-Bhutto" },
    ],
    relatedPeople: ["Fatima Jinnah", "Jahangir Khan"],
  },
  {
    id: "malala-yousafzai",
    name: "Malala Yousafzai",
    urduName: "ملالہ یوسفزئی",
    category: "Educator",
    province: "Khyber Pakhtunkhwa",
    city: "Mingora",
    coordinates: [34.7717, 72.3602],
    lifeDates: "1997-",
    impactScore: 91,
    era: "2001-Present",
    portrait: "https://commons.wikimedia.org/wiki/Special:FilePath/Malala%20Yousafzai%202015.jpg?width=240",
    bio: "Education activist and Nobel Peace Prize laureate whose advocacy for girls' schooling made Swat part of a global rights conversation.",
    achievements: [
      "Shared the 2014 Nobel Peace Prize",
      "Founded Malala Fund",
      "Advocates globally for girls' education",
    ],
    sources: [
      { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Malala_Yousafzai" },
      { label: "Nobel Prize", url: "https://www.nobelprize.org/prizes/peace/2014/yousafzai/facts/" },
    ],
    relatedPeople: ["Fatima Jinnah", "Arfa Karim"],
  },
  {
    id: "nusrat-fateh-ali-khan",
    name: "Nusrat Fateh Ali Khan",
    urduName: "نصرت فتح علی خان",
    category: "Musician",
    province: "Punjab",
    city: "Faisalabad",
    coordinates: [31.4504, 73.135],
    lifeDates: "1948-1997",
    impactScore: 90,
    era: "1971-2000",
    portrait: "https://commons.wikimedia.org/wiki/Special:FilePath/Nusrat%20Fateh%20Ali%20Khan.jpg?width=240",
    bio: "Qawwali maestro whose voice carried South Asian devotional music onto the world's largest stages.",
    achievements: [
      "Known internationally as Shahenshah-e-Qawwali",
      "Expanded global audiences for qawwali",
      "Recognized among the major vocalists of the 20th century",
    ],
    sources: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Nusrat_Fateh_Ali_Khan" }],
    relatedPeople: ["Noor Jehan", "Mehdi Hassan"],
  },
  {
    id: "noor-jehan",
    name: "Noor Jehan",
    urduName: "نور جہاں",
    category: "Musician",
    province: "Punjab",
    city: "Kasur",
    coordinates: [31.1156, 74.4467],
    lifeDates: "1926-2000",
    impactScore: 88,
    era: "1947-1970",
    portrait: "https://commons.wikimedia.org/wiki/Special:FilePath/Noor%20Jehan.jpg?width=240",
    bio: "Singer and actor known as Malika-e-Tarannum, central to the sound of Pakistani film and patriotic music.",
    achievements: [
      "Recorded thousands of songs",
      "Defined generations of Pakistani film music",
      "Received major national honors",
    ],
    sources: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Noor_Jehan" }],
    relatedPeople: ["Nusrat Fateh Ali Khan", "Mehdi Hassan"],
  },
  {
    id: "sadequain",
    name: "Sadequain",
    urduName: "صادقین",
    category: "Artist",
    province: "Sindh",
    city: "Karachi",
    coordinates: [24.8459, 67.0344],
    lifeDates: "1930-1987",
    impactScore: 86,
    era: "1947-1970",
    portrait: "https://commons.wikimedia.org/wiki/Special:FilePath/Sadequain.jpg?width=240",
    bio: "Painter, calligrapher, and muralist whose monumental works gave modern Pakistani art a bold public language.",
    achievements: [
      "Created major public murals",
      "Reimagined calligraphy in modern form",
      "Received national and international recognition",
    ],
    sources: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Sadequain" }],
    relatedPeople: ["Abdur Rahman Chughtai", "Faiz Ahmed Faiz"],
  },
  {
    id: "atta-ur-rahman",
    name: "Atta-ur-Rahman",
    urduName: "عطا الرحمٰن",
    category: "Scientist",
    province: "Sindh",
    city: "Karachi",
    coordinates: [24.9411, 67.1206],
    lifeDates: "1942-",
    impactScore: 82,
    era: "1971-2000",
    portrait: "https://commons.wikimedia.org/wiki/Special:FilePath/Atta-ur-Rahman.jpg?width=240",
    bio: "Organic chemist and science administrator associated with major reforms in higher education and research capacity.",
    achievements: [
      "Published extensively in natural product chemistry",
      "Led major higher education and research reforms",
      "Promoted research infrastructure and digital libraries",
    ],
    sources: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Atta-ur-Rahman_(chemist)" }],
    relatedPeople: ["Abdus Salam", "Arfa Karim"],
  },
  {
    id: "ahmed-faraz",
    name: "Ahmed Faraz",
    urduName: "احمد فراز",
    category: "Poet",
    province: "Khyber Pakhtunkhwa",
    city: "Kohat",
    coordinates: [33.5869, 71.4429],
    lifeDates: "1931-2008",
    impactScore: 80,
    era: "1947-1970",
    portrait: "https://commons.wikimedia.org/wiki/Special:FilePath/Ahmad%20Faraz.jpg?width=240",
    bio: "Modern Urdu poet whose romantic and political verse became part of Pakistan's popular literary memory.",
    achievements: [
      "Published widely read poetry collections",
      "Received Hilal-e-Imtiaz",
      "Served in literary and cultural institutions",
    ],
    sources: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Ahmad_Faraz" }],
    relatedPeople: ["Faiz Ahmed Faiz", "Patras Bokhari"],
  },
  {
    id: "ruth-pfau",
    name: "Ruth Pfau",
    urduName: "رتھ فاؤ",
    category: "Humanitarian",
    province: "Sindh",
    city: "Karachi",
    coordinates: [24.8949, 67.0281],
    lifeDates: "1929-2017",
    impactScore: 79,
    era: "1971-2000",
    portrait: "https://commons.wikimedia.org/wiki/Special:FilePath/Ruth%20Pfau.jpg?width=240",
    bio: "Physician and humanitarian whose work transformed leprosy treatment and public health service in Pakistan.",
    achievements: [
      "Led Pakistan's leprosy control efforts",
      "Worked with Marie Adelaide Leprosy Centre",
      "Received a state funeral in Pakistan",
    ],
    sources: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Ruth_Pfau" }],
    relatedPeople: ["Abdul Sattar Edhi", "Hakeem Muhammad Saeed"],
  },
  {
    id: "jahangir-khan",
    name: "Jahangir Khan",
    urduName: "جہانگیر خان",
    category: "Athlete",
    province: "Khyber Pakhtunkhwa",
    city: "Peshawar",
    coordinates: [34.0151, 71.5249],
    lifeDates: "1963-",
    impactScore: 78,
    era: "1971-2000",
    portrait: "https://commons.wikimedia.org/wiki/Special:FilePath/Jahangir%20Khan.jpg?width=240",
    bio: "Squash legend whose dominance made Pakistan a defining name in the sport for decades.",
    achievements: [
      "Won multiple World Open and British Open titles",
      "Recorded one of sport's longest winning streaks",
      "Elevated Pakistan's global sporting reputation",
    ],
    sources: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Jahangir_Khan" }],
    relatedPeople: ["Benazir Bhutto", "Malala Yousafzai"],
  },
  {
    id: "hakeem-saeed",
    name: "Hakeem Muhammad Saeed",
    urduName: "حکیم محمد سعید",
    category: "Educator",
    province: "Sindh",
    city: "Karachi",
    coordinates: [24.927, 67.052],
    lifeDates: "1920-1998",
    impactScore: 75,
    era: "1947-1970",
    portrait: "https://commons.wikimedia.org/wiki/Special:FilePath/Hakim%20Mohammed%20Said.jpg?width=240",
    bio: "Scholar, philanthropist, and institution builder associated with education, medicine, publishing, and civic learning.",
    achievements: [
      "Founded Hamdard Pakistan",
      "Established Madinat al-Hikmah",
      "Promoted children's education and public knowledge",
    ],
    sources: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Hakim_Said" }],
    relatedPeople: ["Abdul Sattar Edhi", "Ruth Pfau"],
  },
  {
    id: "bapsi-sidhwa",
    name: "Bapsi Sidhwa",
    urduName: "باپسی سدھوا",
    category: "Writer",
    province: "Punjab",
    city: "Lahore",
    coordinates: [31.5497, 74.3436],
    lifeDates: "1938-2024",
    impactScore: 73,
    era: "1971-2000",
    portrait: "https://commons.wikimedia.org/wiki/Special:FilePath/Bapsi%20Sidhwa.jpg?width=240",
    bio: "Novelist whose English-language fiction brought Partition, Lahore, and Parsi identity into global literary view.",
    achievements: [
      "Authored Ice-Candy-Man and The Crow Eaters",
      "Helped define Pakistani English fiction",
      "Received major literary recognition",
    ],
    sources: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Bapsi_Sidhwa" }],
    relatedPeople: ["Patras Bokhari", "Faiz Ahmed Faiz"],
  },
  {
    id: "arfa-karim",
    name: "Arfa Karim",
    urduName: "ارفع کریم",
    category: "Scientist",
    province: "Punjab",
    city: "Faisalabad",
    coordinates: [31.418, 73.079],
    lifeDates: "1995-2012",
    impactScore: 70,
    era: "2001-Present",
    portrait: "https://commons.wikimedia.org/wiki/Special:FilePath/Arfa%20Karim.jpg?width=240",
    bio: "Technology prodigy who became a national symbol for youth potential in computing and education.",
    achievements: [
      "Became a Microsoft Certified Professional at age nine",
      "Inspired Pakistani youth in technology",
      "Recognized through institutions and awards bearing her name",
    ],
    sources: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Arfa_Karim" }],
    relatedPeople: ["Abdus Salam", "Malala Yousafzai"],
  },
  {
    id: "patras-bokhari",
    name: "Patras Bokhari",
    urduName: "پطرس بخاری",
    category: "Writer",
    province: "Khyber Pakhtunkhwa",
    city: "Peshawar",
    coordinates: [34.0124, 71.5785],
    lifeDates: "1898-1958",
    impactScore: 68,
    era: "Pre-1947",
    portrait: "https://commons.wikimedia.org/wiki/Special:FilePath/Patras%20Bokhari.jpg?width=240",
    bio: "Humorist, broadcaster, diplomat, and educator remembered for elegant Urdu prose and institution-building.",
    achievements: [
      "Authored Patras Ke Mazameen",
      "Served as principal of Government College Lahore",
      "Represented Pakistan at the United Nations",
    ],
    sources: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Patras_Bokhari" }],
    relatedPeople: ["Ahmed Faraz", "Bapsi Sidhwa"],
  },
  {
    id: "khawaja-ghulam-farid",
    name: "Khawaja Ghulam Farid",
    urduName: "خواجہ غلام فرید",
    category: "Poet",
    province: "Punjab",
    city: "Kot Mithan",
    coordinates: [28.9667, 70.3833],
    lifeDates: "1845-1901",
    impactScore: 74,
    era: "Pre-1947",
    portrait: "https://commons.wikimedia.org/wiki/Special:FilePath/Khawaja%20Ghulam%20Farid.jpg?width=240",
    bio: "Sufi poet of the Saraiki tradition whose verse remains central to southern Punjab's literary and spiritual culture.",
    achievements: [
      "Wrote influential Kafi poetry",
      "Major figure in Saraiki literature",
      "Linked poetry, spirituality, and regional identity",
    ],
    sources: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Khawaja_Ghulam_Farid" }],
    relatedPeople: ["Allama Muhammad Iqbal", "Faiz Ahmed Faiz"],
  },
];

export function minimumScoreForZoom(zoom) {
  if (zoom < 5) return 90;
  if (zoom < 7) return 75;
  if (zoom < 9) return 65;
  return 0;
}

export function tierForScore(score) {
  if (score >= 90) return "legendary";
  if (score >= 75) return "major";
  if (score >= 65) return "regional";
  return "local";
}
